export const SESSION_REQUEST = "SESSION_REQUEST";
export const SESSION_REMOVING = "SESSION_REMOVING";
export const SESSION_REMOVED = "SESSION_REMOVED";
export const SESSION_SUCCESS = "SESSION_SUCCESS";
export const SESSION_FAILED = "SESSION_FAILED";
